# This is a basic workflow that is manually triggered
name: Publish to NuGet

on:
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ConverterHelper/ConverterHelper.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: ConverterHelper
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
